#!/bin/bash

# Script untuk menampilkan CORRECT redirect URIs untuk Google Cloud Console
# Jalankan: bash scripts/correct-google-oauth-uris.sh

echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "   ✅ REDIRECT URIs YANG BENAR untuk Google Cloud Console"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "⚠️  PERHATIAN:"
echo "   Google Cloud Console HANYA menerima HTTP/HTTPS URIs"
echo "   Custom schemes (exp://, parentingai://) TIDAK BISA digunakan"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "🔗 LANGKAH 1: Buka Google Cloud Console"
echo "   https://console.cloud.google.com/apis/credentials"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "📝 LANGKAH 2: Pilih Web Client ID (bukan Android/iOS)"
echo "   Pastikan Anda edit 'Web application' OAuth client"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "✅ LANGKAH 3: Tambahkan HANYA URI ini:"
echo ""
echo "   https://gbcxzkgzhylpbmzbymwj.supabase.co/auth/v1/callback"
echo ""
echo "   (COPY PASTE URI di atas - ini satu-satunya yang perlu ditambahkan)"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "❌ JANGAN tambahkan URI berikut (akan ditolak Google):"
echo "   • exp://192.168.1.4:8081       ❌ Custom scheme tidak diterima"
echo "   • parentingai://               ❌ Custom scheme tidak diterima"
echo "   • parentingai://auth-callback  ❌ Custom scheme tidak diterima"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "🔑 LANGKAH 4: Setup di Supabase Dashboard"
echo "   https://supabase.com/dashboard/project/gbcxzkgzhylpbmzbymwj/auth/providers"
echo ""
echo "   1. Enable 'Google' provider"
echo "   2. Masukkan Web Client ID dari Google Console"
echo "   3. Masukkan Web Client Secret dari Google Console"
echo "   4. SAVE"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "📱 LANGKAH 5: Configure Redirect URLs di Supabase"
echo "   https://supabase.com/dashboard/project/gbcxzkgzhylpbmzbymwj/auth/url-configuration"
echo ""
echo "   Site URL:"
echo "   parentingai://auth-callback"
echo ""
echo "   Redirect URLs (tambahkan satu per satu):"
echo "   parentingai://auth-callback"
echo "   exp://192.168.1.4:8081"
echo "   http://localhost:8081"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "👥 LANGKAH 6: Tambahkan Test User"
echo "   https://console.cloud.google.com/apis/credentials/consent"
echo ""
echo "   1. Scroll ke 'Test users'"
echo "   2. Klik '+ ADD USERS'"
echo "   3. Masukkan: artconcept91@gmail.com"
echo "   4. SAVE"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "🔄 LANGKAH 7: Restart Expo"
echo ""
echo "   npx expo start --clear"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "📚 PENJELASAN:"
echo ""
echo "   Google OAuth Flow untuk Native Apps:"
echo "   1. App opens browser → Google login page"
echo "   2. User signs in → Google redirects to Supabase callback"
echo "   3. Supabase validates → Redirects back to app (parentingai://)"
echo "   4. App receives session → User logged in ✅"
echo ""
echo "   Jadi Google hanya perlu tahu tentang Supabase URL,"
echo "   BUKAN tentang custom app scheme!"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "⏰ TUNGGU 2-3 MENIT setelah save"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "💡 RINGKASAN:"
echo "   • Google Console: Hanya Supabase callback URL"
echo "   • Supabase: Custom schemes untuk redirect ke app"
echo "   • App: Menggunakan Supabase sebagai OAuth proxy"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
