#!/bin/bash

# Script untuk menampilkan redirect URIs yang perlu ditambahkan ke Google Cloud Console
# Jalankan: bash scripts/show-google-oauth-uris.sh

echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "   🔑 GOOGLE OAUTH REDIRECT URIs - WAJIB DITAMBAHKAN"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "❌ ERROR: redirect_uri=exp://192.168.1.4:8081"
echo "   Redirect URI ini belum terdaftar di Google Cloud Console"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "🔗 LANGKAH 1: Buka Google Cloud Console"
echo "   https://console.cloud.google.com/apis/credentials"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "📋 LANGKAH 2: Edit OAuth 2.0 Client ID"
echo "   1. Klik OAuth 2.0 Client ID yang Anda gunakan"
echo "   2. Scroll ke 'Authorized redirect URIs'"
echo "   3. Klik '+ ADD URI'"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "📝 LANGKAH 3: Tambahkan URI berikut (COPY PASTE):"
echo ""
echo "   exp://192.168.1.4:8081"
echo ""
echo "   https://gbcxzkgzhylpbmzbymwj.supabase.co/auth/v1/callback"
echo ""
echo "   parentingai://"
echo ""
echo "   parentingai://auth-callback"
echo ""
echo "   https://auth.expo.io/@yourusername/parenting-ai"
echo "   (Ganti 'yourusername' dengan Expo username Anda)"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "✅ LANGKAH 4: Klik tombol SAVE"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "👥 LANGKAH 5: Tambahkan Test User"
echo "   https://console.cloud.google.com/apis/credentials/consent"
echo ""
echo "   1. Scroll ke 'Test users'"
echo "   2. Klik '+ ADD USERS'"
echo "   3. Masukkan: artconcept91@gmail.com"
echo "   4. SAVE"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "🔄 LANGKAH 6: Restart Expo"
echo "   Tekan Ctrl+C di terminal Expo, lalu:"
echo ""
echo "   npx expo start --clear"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "⏰ TUNGGU 2-3 MENIT setelah save (propagation time)"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "💡 TIPS:"
echo "   • Redirect URI harus PERSIS sama (case-sensitive)"
echo "   • TIDAK ada trailing slash"
echo "   • IP address (192.168.1.4) akan berubah jika ganti WiFi"
echo "   • Untuk production, gunakan custom scheme (parentingai://)"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
